init:
  - git config --global core.autocrlf input

environment:
  nodejs_version: "9"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
test_script:
  - node --version
  - npm --version
  - cmd: npm test

build: off